### ISSUE TITLE
PowerArgs, help implementing a "Help" option...

### ISSUE THREAD

**Issue by StanleyGoldman** [adamabdelhamed/PowerArgs#60]
I'm trying to create an option that would output the usage template and exit the program.
I would like additional arguments to prompt if missing, if Help was not flagged.
If the user does not specify the Help flag, it should then prompt the user for the other arguments.
In my case below, OtherArg prompts as expected, but the resulting value is always null.

    public class TestArgs
    {
        [ArgShortcut("?")]
        public bool Help { get; set; }

        [ArgRequired(PromptIfMissing = true, IfNot = "Help")]
        public string OtherArg { get; set; }
    }

    class Program
    {
        private static void Main(string[] args)
        {
            var testArgs = Args.Parse<TestArgs>(args);
            if (testArgs .Help)
            {
                Console.WriteLine(ArgUsage.GenerateUsageFromTemplate<TestArgs>());
                return;
            }
        }
    }

**Comment by adamabdelhamed** [comment]
PowerArgs does exactly what you want, but it means making a few changes to your program.

1 - Add the [HelpHook] attribute to your bool property called Help.
2 - Instead of using Args.Parse use Args.InvokeMain and move your main method to TestArgs.
3 - [Optional] - Add ArgExceptionBehavior attribute to your TestArgs class so that user exceptions automatically get the usage printed out.

Here is your code rewritten to support this.

    [ArgExceptionBehavior(ArgExceptionPolicy.StandardExceptionHandling)]
    public class TestArgs
    {
        [ArgShortcut("?"), HelpHook]
        public bool Help { get; set; }

        [ArgRequired(PromptIfMissing = true, IfNot = "Help")]
        public string OtherArg { get; set; }

        public void Main(string[] args)
        {
            var testArgs = Args.Parse<TestArgs>(args);
            if (testArgs.Help)
            {
                Console.WriteLine(ArgUsage.GenerateUsageFromTemplate<TestArgs>());
                return;
            }
        }
    }

    class Program
    {
        private static void Main(string[] args)
        {
            Args.InvokeMain<TestArgs>(args);
        }
    }

**Comment by adamabdelhamed** [comment]
Minor edit made above

**Comment by adamabdelhamed** [comment]
Also note that TestArgs.Main won't be called if the help hook detects the -?

**Comment by StanleyGoldman** [comment]
Thanks dude.
I definitely didn't finish reading Readme.md before i started poking around.
Thanks for the answer.

**Comment by StanleyGoldman** [comment]
I followed your directions and they worked. 

But I ran into a similar issue by doing something that I feel should work.
I am trying to add a flag that outputs the application version and stops.

Any value with IfNot="Version" ends up being null

    [ArgRequired(PromptIfMissing = true, IfNot = "Version")]
    public string OtherArg { get; set; }

I dont feel I should have to re-implement a clone of HelpHook just for this purpose.

**Comment by StanleyGoldman** [comment]
So I tried to inherit ArgHook to a class called VersionHook based on what I saw in HelpHook.
My output never appears, and when context.CancelAllProcessing() is called, the standard help appears.

    public class VersionHook : ArgHook
    {
        public override void BeforePopulateProperty(HookContext context)
        {
            base.BeforePopulateProperty(context);
            if (context.CurrentArgument.ArgumentType != typeof(bool))
                throw new InvalidArgDefinitionException(typeof(VersionHook).Name + " attributes can only be used with boolean properties or parameters");
        }

        public override void AfterPopulateProperty(HookContext context)
        {
            base.AfterPopulateProperty(context);
            if (!(context.CurrentArgument.RevivedValue is bool) || !(bool)context.CurrentArgument.RevivedValue)
                return;

            context.CancelAllProcessing();
        }

        public override void AfterCancel(HookContext context)
        {
            base.AfterCancel(context);

            var usage = new ConsoleString();
            var assemblyName = Assembly.GetEntryAssembly().GetName();

            usage.AppendUsingCurrentFormat(string.Format("{0} v{1}", assemblyName.FullName, assemblyName.Version));
            usage.Write();
        }
    }

**Comment by adamabdelhamed** [comment]
ConsoleString objects are immutable, like strings.  So when you're doing usage.Append...() that is returning a new ConsoleString, not updating the usage variable.  Your code is running (I tried it), but you're writing an empty string.

**Comment by adamabdelhamed** [comment]
And you probably want to use WriteLine() instead of Write().

**Comment by adamabdelhamed** [comment]
For the issue of the help being written, I think you found a bug.  Thanks!  I just fixed it, but I haven't published it yet.  Give me a couple of days since I have some other work going in.  The problem is that the [HelpHook] isn't tracking whether or not it was the hook that initiated the cancel.  So it is always showing the usage even if another hook initiated the cancel.  

You will have the same issue in your VersionHook.  You'll need to set an instance level boolean field to true or false somewhere in AfterPopulateProperty before you call context.CancelAllProcessing().  Then, when AfterCancel() gets called you should only print your version info if your Boolean is true.

If that doesn't make sense then wait for my check in for [HelpHook] and you'll see what I mean.

Thanks,
Adam

**Comment by StanleyGoldman** [comment]
Thanks for the help and I'm glad to help as well!

**Comment by adamabdelhamed** [comment]
fix published
