### ISSUE TITLE
exeCopyright, exeDescription, exeProduct and exeVersion in addition to exeName

### ISSUE THREAD

**Issue by isolaol** [adamabdelhamed/PowerArgs#66]
Hi Adam,

First, thanks for developing this interesting library!

I am used to start usage text with unix style header:

```
product name version
copyright
description
```

For example:
```
Image Manager 1.1.0.25342
Copyright © Fun Company Ltd 2014-2015
Organize your images into directory structure and attach tags to them.
```

This information usually comes from attributes in AssemblyInfo.cs (or AssemblyInfo.vb in VB.Net projects). Those attributes are AssemblyTitle, AssemblyDescription, AssemblyCompany, AssemblyCompany, AssemblyCopyright, AssemblyTrademark, AssemblyVersion and AssemblyFileVersion.

I suggest that you expose the values of those attributes via template data model. Having prefix 'exe' is just fine if you like to keep new property names consistent with the existing exeName property.

Such enhancement would allow myself to write custom usage template with the header I like.

Kind regards,
Olli-Pekka Isola

**Comment by adamabdelhamed** [comment]
This is a good idea.  I'll add this when I get a chance.  I can even update the default templates to include these values if present.

Thanks,
Adam

**Comment by adamabdelhamed** [comment]
I added the fields, but I didn't modify the default templates because I'm not sure how to format it in a way that will work for most people.  You can always copy and modify the default usage template which is in PowerArgs.Resources.DefaultConsoleUsageTemplate to include these values in your usage documentation.  

I have documentation for how to do this [here](https://github.com/adamabdelhamed/PowerArgs#generate-usage-documentation-from-templates-built-in-or-custom).
