### ISSUE TITLE
Context switching (different behaviors in different "screens")

### ISSUE THREAD

**Issue by rmnblm** [adamabdelhamed/PowerArgs#70]
First of all: PowerArgs is great (at least what I have seen so far)!

I don't know how to describe my problem so I just jump in an example.
I want to write "config profile" and want to switch my context so that I now can enter "show" and it will show all profiles or "edit 1" to edit the profile with ID 1. 
If I want to go back, I just enter "end" and I'm going back to a main screen where I can enter "config foobar" or again "config profile". It's like switching the context.

Do you know what I try to achieve? :)

**Comment by adamabdelhamed** [comment]
Sorry for the long delay on answering this. It seems like you want to use the REPL feature.  You could keep track of the context after each invocation and then update TabCompletion.Indicator so that the command line prints out your context before each iteration of the REPL loop.

If this is still something you're trying to achieve then let me know.
