### ISSUE TITLE
async/await support

### ISSUE THREAD

**Issue by abbottdev** [adamabdelhamed/PowerArgs#76]
What options are available for async/await support? 

I'm writing a desktop application that can be run with command line arguments - ideally I want to invoke actions on that application in an async fashion without blocking the UI thread.

It looks like PowerArgs has been mainly suited to Console type applications - would be interested if anyone else has worked on something similar, whether I'm not solving a problem correctly, or, if they think it's a worthwhile addition.

If it was to be added, I was thinking something like adding a new project, `PowerArgs.Async` which would contain async extensions to the InvokeAction/Main methods.

Thoughts?

**Comment by adamabdelhamed** [comment]
PowerArgs is absolutely for console applications.  If you are building your own console UI or do something similar then I can see why you might want this.  

I've wanted to add Async versions of all the parse and invoke methods in the Args class for a while.  I can add it now.  I'll also modify the code a bit so that if your action code returns a Task then I'll wait on it.  These two changes should let you use async and await in a few places:

 1 - The code where you call `Args.InvokeAction(...)` or `Args.Parse(...)` can now be `await Args.InvokeActionAsync(...)` or `await Args.ParseAsync(...)`.
 2 - Your action code (or instance level Main if that's what you use) can now be async.  For example:

```cs 
    [ArgActionMethod]
    public void MyAction(MyActionArgs args)
    {
        // your action code here
    }
```
can become 

```cs
    [ArgActionMethod]
    public async Task MyActionAsync(MyActionArgs args)
    {
        // your action code with full await support here
    }
```
